var myCars = [
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01001</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92011</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">张江实训专用车</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01001</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92022</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">张江实训专用车</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01001</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92033</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">张江实训专用车</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01001</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93442</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">张江实训专用车</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01001</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93453</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">张江实训专用车</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01001</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">94102</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">张江实训专用车</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01001</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">94113</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">张江实训专用车</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01001</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">94121</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">张江实训专用车</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01002</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93121</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">含特殊扩编车厢、曾为备件车，最后一列扩编</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01002</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93262</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">含特殊扩编车厢、曾为备件车，最后一列扩编</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01002</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93273</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">含特殊扩编车厢、曾为备件车，最后一列扩编</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01002</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title"><em>14652</em></span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">含特殊扩编车厢、曾为备件车，最后一列扩编</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01002</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title"><em>14663</em></span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">含特殊扩编车厢、曾为备件车，最后一列扩编</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01002</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92102</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">含特殊扩编车厢、曾为备件车，最后一列扩编</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01002</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93233</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">含特殊扩编车厢、曾为备件车，最后一列扩编</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01002</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93311</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">含特殊扩编车厢、曾为备件车，最后一列扩编</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01003</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92131</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01003</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92142</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01003</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92153</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01003</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">94022</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01003</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">94033</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01003</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92162</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01003</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92173</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01003</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92181</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01004</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92191</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01004</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92202</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01004</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92213</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01004</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">94202</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01004</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">94213</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01004</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92222</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01004</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92233</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01004</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92241</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01005</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93011</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01005</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93022</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01005</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93033</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01005</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">94162</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01005</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">94173</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01005</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93042</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01005</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93053</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01005</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">93061</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01006</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92061</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01006</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92053</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01006</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92042</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01006</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">94053</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01006</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92042</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01006</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92093</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01006</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92082</span></div><div class="mdui-divider"></div>',
    '<div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">1号线</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01A01（老老八）</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">01006</span></div><div class="mdui-chip mdui-ripple"><span class="mdui-chip-title">92071</span></div><div class="mdui-divider"></div>',
];
function findone() {
    mykey = document.getElementById("mykeyword").value;
    myfind = document.getElementById("myfind").value;
    myfind = "";
    for (i in myCars) {
        if (myCars[i].search(mykey) >= 0) { myfind = myfind + myCars[i] + "" }
    }
    document.getElementById("myfind").innerHTML = myfind;
}
